# Generated by Django 5.1.3 on 2025-04-19 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('skin_condition', models.TextField()),
                ('condition_known', models.BooleanField()),
                ('diagnosis_year', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('affected_area', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='medical_forms/')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
